### ISSUE TITLE
Issue with Dot Notation in DatabaseSettingStore.php

### ISSUE THREAD

**Issue by bequiet88** [anlutro/laravel-settings#11]
Hey Anlutro,

Thank you very much for your handy settings library.

I came accross a problem in the write() function of DatabaseSettingStore. The error occurs when I use setting keys with dot notation. In case such a setting item is updated, the current write method does not execute the update in line 96 but the insert in line 110. This is due the "isset IF condition" in line 95 that always returns false in case $data is a multi-dimensional array because the $key contains dot notation. Automatic resolution of a dot notation is apperently not supported by isset().

My suggested fix uses Laravels array_dot() function (see http://laravel.com/docs/4.2/helpers) to flatten the $data array in order to align the keys read from the database and those present in the $data array. The following write() function is working for me:

        protected function write(array $data)
	{
		$keys = $this->newQuery()
			->lists('key');	

		$updateData = array();
		$dotData = array_dot($data);

		foreach ($keys as $key) {
			if (isset($dotData[$key])) {
				$updateData[$key] = $dotData[$key];
				unset($dotData[$key]);
			}
		}

		foreach ($updateData as $key => $value) {
			$this->newQuery()
				->where('key', '=', $key)
				->update(array('value' => $value));
		}

		if ($dotData) {
			$dbData = $this->prepareWriteData($data);
			$this->newQuery(true)
				->insert($dbData);
		}
	}

If you agree to this solution, please commit a fix for it to your dev-master in packagist so that I can use it with Composer.

Thank you very much,
Jochen

**Comment by anlutro** [comment]
Hello, thanks for letting me know. This ended up being a bug in the test suite which didn't properly register if the correct things were being inserted/updated. 0d0cbd5 in master should fix the issue, if you could see if the fix works for you that would be great.

**Comment by bequiet88** [comment]
Hi Andreas,

I appreciate your quick help on this matter. But it's still not working for me. Your fix in DatabaseSettingStore actually raised a couple of new issues for me:

1. Line 96
array_set() must fill $updateData not $data

2. Line 97
static::arrayUnset() only removes the deepest level elements of the array.
Given this array:
nest.one
nest.two
nest.three
...
In case all 2nd level elements of nest are removed, the $data array still holds the "nest" element. Because of this, the IF-condition in line 107 will not be evaluated to false even though it is actually empty.

3. Line 101
If I change in line 96 in array_set() $data to (the correct) $updateData, then $updateData becomes also an nested array and in the update foreach (lines 101-105). The current update code cannot handle a nested array and, thus, leads to errors.

Why not use the array_dot() function? Is this function not working for single level arrays?

Thanks in advance for another quick hot fix!
Jochen

**Comment by anlutro** [comment]
Hmm, looking back I'm not sure what I was thinking - I was hesitant to use array_dot for some reason but I was clearly already using it in `prepareWriteData`...

Anyway, you're right, I wrote a functional test that uses an in-memory database and your suggested fix code was more or less correct. Try updating now.

**Comment by bequiet88** [comment]
Hi, Thanks for fixing it again. It's now working for me :+1:

**Comment by anlutro** [comment]
Great, tagged a new version so you don't have to use `dev-master`.
